[project]
name = "mm-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.6.0",
    "mmanager==2.3.4",
    "ipython>=8.12.0",
]
